services:
  # 🟩 Backend API
  - type: web
    name: backend
    runtime: node
    rootDir: app/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: PYTHON_API
        value: https://python-api.onrender.com/process-image
      - key: REDIS_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_EXPIRY
        sync: false
      - key: MAILTRAP_SMTP_HOST
        sync: false
      - key: MAILTRAP_SMTP_PORT
        sync: false
      - key: MAILTRAP_SMTP_USER
        sync: false
      - key: MAILTRAP_SMTP_PASS
        sync: false
      - key: MONGODB_URL
        sync: false


  # 🟨 Worker (BullMQ)
  - type: worker
    name: worker
    runtime: node
    rootDir: app/backend
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: REDIS_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        sync: false
      - key: PYTHON_API
        value: https://python-api.onrender.com/process-image

  # 🐍 Python API
  - type: web
    name: python-api
    runtime: python
    rootDir: services
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000

  # 🟥 Frontend
  - type: web
    name: frontend
    runtime: static
    rootDir: app/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_LINK
        value: https://backend.onrender.com